# Generated by Django 2.0.5 on 2019-06-17 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('language', '0002_auto_20190617_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warlpiri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translation_text', models.CharField(max_length=200)),
                ('phrase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language.Phrase')),
            ],
        ),
    ]
